authors/urls.py
from django.urls import path
from authors import views

app_name = 'authors'

urlpatterns = [ 
    path('register/',views.register_view, name='register'),
    path('register/create/',views.register_created, name='create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.home, name='home'), 
    path('recipes/search/', views.search, name='search'), 
    path('recipes/<int:id>/', views.recipes, name='recipe'), 
    path('recipes/category/<int:id>/', views.category, name='category'), 
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name
    
class Recipe(models.Model):
    class Meta:
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updatad_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    def __str__(self): 
        return self.title

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import Http404, HttpResponse
from . import models
from django.db.models import Q
from utils.pagination_func import make_pagination_range, make_pagination
import os
from django.contrib import messages


PER_PAGE = int(os.environ.get('PER_PAGE', 6)) 

def home(request):
    recipes = models.Recipe.objects.all().filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    context ={
        'page_title': 'Home',
        'recipes': page_obj,
        'pagination_range': pagination_range
    }
    return render(request, 'recipes/pages/home.html', context)


def recipes(request, id):
    recipe = models.Recipe.objects.filter(id=id).first()
    recipe = get_object_or_404(models.Recipe.objects.filter(id=id, is_published=True))
    page_title = f'Receita - {recipe.title}' #type: ignore 

    context ={
        'page_title': page_title,
        'recipe': recipe,
        'one_page': True,
    }

    return render(request, 'recipes/pages/recipes_page.html', context)

def category(request, id):
    # recipe = models.Recipe.objects.filter(category__id=id, is_published=True)
    # if not recipe:
    #     raise Http404('Not found 🙁')
    recipe = get_list_or_404(
        models.Recipe.objects.filter(
        category__id=id, 
        is_published=True).order_by('-id'),
    )
    page_obj, pagination_range = make_pagination(request, recipe, PER_PAGE)
    
    page_title = f'Categorias - {recipe[0].category.name}'#type: ignore 
    context ={
        'page_title': page_title,
        'recipes': page_obj,
        'pagination_range': pagination_range,

    }

    return render(request, 'recipes/pages/home.html', context)

def search(request):
    search_term = request.GET.get('q', '').strip()

        
    if not search_term:
        raise Http404 
    page_title = f'Search for "{search_term}"'
    recipes = models.Recipe.objects.filter(
        Q(        
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term) |
            Q(author__first_name__icontains=search_term) |
            Q(author__last_name__icontains=search_term) |
            Q(category__name__icontains=search_term)
        ),
        is_published=True

    ).order_by('-id')
    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    context ={
        'page_title': page_title,
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}'
    }
    return render(request,'recipes/pages/search.html', context)

recipes/templates/recipes/partials/_head.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css" integrity="sha512-siarrzI1u3pCqFG2LEzi87McrBmq6Tp7juVsdmGY1Dr8Saw+ZBAzDzrGwX3vgxX1NkioYNCFOVC0GpDPss10zQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/brands.min.css" integrity="sha512-W/zrbCncQnky/EzL+/AYwTtosvrM+YG/V6piQLSe2HuKS6cmbw89kjYkp3tWFn1dkWV7L1ruvJyKbLz73Vlgfg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/solid.min.css" integrity="sha512-P9pgMgcSNlLb4Z2WAB2sH5KBKGnBfyJnq+bhcfLCFusrRc4XdXrhfDluBl/usq75NF5gTDIMcwI1GaG5gju+Mw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'global/styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <title>{{page_title}} | by Django</title>
</head>

recipes/templates/recipes/partials/_recipes.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{recipe.cover.url}}" alt="temporario">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            {% if one_page is not True %}
                <a href="{% url 'recipes:recipe' recipe.id %}">
                    {{recipe.title}}
                </a>
            {% else %}
                {{recipe.title}}
            {% endif %}
        </h2>
    </div>
    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{recipe.author.first_name}} {{recipe.author.last_name}}
                {% else %}
                    {{recipe.author}}
                {% endif %}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at}}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        {% if one_page %}
            {% if recipe.preparation_steps_is_html is True %}
                {{recipe.preparation_steps | safe }}
            {% else %}
                {{recipe.preparation_steps | linebreaks}}
            {% endif %}
        {% else %}
            <p>{{recipe.description}}</p>
        {% endif %}
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if one_page is not True%}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

</div>